# 1. Create a 3*3*3  array with random values

In [4]:
import numpy as np
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.87676025 0.10620397 0.29288434]
  [0.00444318 0.19729968 0.43851939]
  [0.87852918 0.83087851 0.16319893]]

 [[0.15750292 0.29884352 0.0541759 ]
  [0.61553692 0.93719235 0.44509564]
  [0.45350142 0.42602872 0.69177423]]

 [[0.38424428 0.51620404 0.77435427]
  [0.60919457 0.08498312 0.09665517]
  [0.68211527 0.09139541 0.67426986]]]


# 2. Create a 5*5 matrix values with 1,2,3,4 just below the diagonal 

In [6]:
import numpy as np

matrix = np.zeros((5, 5), dtype=int)


for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8*8 matrix and fill it with a checkboard pattern 

In [7]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1 
matrix[::2, 1::2] = 1 

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5*5 random matrix

In [9]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.38244764 0.02045042 0.85535498 0.48555996 0.83577477]
 [0.94945168 0.73723325 0.00186658 0.09530621 0.55974828]
 [0.64957764 0.67837192 0.93654366 0.1453245  0.87833007]
 [0.76601846 0.9760151  0.2764114  0.14055151 0.04436542]
 [0.32763655 0.63556271 0.52952403 0.1911201  0.34805661]]
After normalization:
[[0.39068074 0.01907701 0.87613786 0.4965294  0.85603805]
 [0.97273166 0.75488148 0.         0.09591928 0.57268649]
 [0.6648997  0.69445812 0.95948109 0.14726493 0.89972265]
 [0.78443057 1.         0.28183056 0.14236528 0.04362665]
 [0.33441509 0.65051285 0.54166017 0.19427584 0.35537706]]


# 5. How to find common values between two arrays

In [10]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [3 4 5]


# 6. How to get dates of yesterday, today and tomorrow?

In [11]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yesterday:  2023-09-21
Today:  2023-09-22
Tomorrow:  2023-09-23


# 7. Consider two random array A and B, Check if they are equal.

In [14]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
array_equal = np.array_equal(x, y)
if array_equal:
    print("Both Arrays Are Equal")
else :
    print("Arrays Are Not Equal")


First array:
[0 0 1 1 1 1]
Second array:
[1 1 0 1 1 0]
Arrays Are Not Equal


# 8. Create a random vector of size 10 and replace the maximum value by 0

In [20]:
import numpy as np
x = np.random.rand(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.50662959 0.39693047 0.62610877 0.55170796 0.63569841 0.51614731
 0.1132556  0.71776648 0.95790205 0.30884434]
Maximum value replaced by 0:
[0.50662959 0.39693047 0.62610877 0.55170796 0.63569841 0.51614731
 0.1132556  0.71776648 0.         0.30884434]


# 9. How to Print all the values of an array?

In [22]:
import numpy as np

x=np.random.rand(2,5)
print(x)

[[0.84195136 0.18731184 0.22390735 0.71036297 0.57758085]
 [0.32005523 0.47938445 0.64490368 0.88836213 0.13819992]]


# 10. Subtract the mean of each row of a matrix

In [23]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the  matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.21294633 0.362104   0.67188081 0.1280547  0.33636405 0.71596344
  0.85444421 0.57514527 0.50497788 0.17198984]
 [0.34460902 0.91285468 0.95591681 0.18548407 0.29628246 0.87739475
  0.13702285 0.42463317 0.84125794 0.7412168 ]
 [0.27814515 0.16429696 0.46824762 0.67278289 0.10516856 0.9833093
  0.19151026 0.45724269 0.94940595 0.58243842]
 [0.15595109 0.42948183 0.23340188 0.28782804 0.85247004 0.26404649
  0.35432784 0.59328727 0.91489638 0.63970527]
 [0.75873167 0.91674726 0.8299936  0.05545542 0.48645038 0.35836087
  0.70149141 0.99747405 0.6858717  0.50945274]]

Subtract the mean of each row of the  matrix:

[[-0.24044072 -0.09128305  0.21849376 -0.32533235 -0.117023    0.26257638
   0.40105715  0.12175822  0.05159082 -0.28139721]
 [-0.22705824  0.34118743  0.38424956 -0.38618319 -0.27538479  0.3057275
  -0.4346444  -0.14703409  0.26959069  0.16954954]
 [-0.20710963 -0.32095782 -0.01700716  0.18752811 -0.38008622  0.49805452
  -0.29374452 -0.02801209  0.4641511

# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [25]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 2. 2. 6. 3. 2. 2. 2. 3. 4.]


# 12. How to get the diagonal of a Dot Product ?

In [26]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

dot_product = np.dot(matrix1, matrix2)

diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)
print("\nDiagonal of Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


# 13. How to find most frequent value in an array?

In [32]:
import numpy as np
x=np.random.randint(0,10,50)
print(x)
print("Most frequent value in the array:")
print(np.bincount(x).argmax())

[9 8 1 3 4 4 7 9 7 9 2 5 7 5 3 0 3 0 6 5 0 2 6 7 4 3 2 8 5 7 8 7 6 6 1 9 0
 7 6 5 5 6 2 2 2 5 0 1 8 0]
Most frequent value in the array:
5


# 14. How to get the n largest values of an array?

In [36]:
import numpy as np
x = np.random.randint(1,40,8)
print("Original array:")
print(x)
np.random.shuffle(x)
n =int(input("enter N value : "))
print("The", n, "largest values in the array are = ")
print (x[np.argsort(x)[-n:]])


Original array:
[36 29 38 12  7 18 39 13]
enter N value : 2
The 2 largest values in the array are = 
[38 39]


# 15. How to create a record array from a regular array? 

In [37]:
import numpy as np
arra1 = np.array([("Ganesh", 88.5, 90),
                 ("Lokesh", 87, 99),
             ("yashwanth", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)


Original arrays:
[['Ganesh' '88.5' '90']
 ['Lokesh' '87' '99']
 ['yashwanth' '85.5' '91']]

Record array;
[(b'Ganesh', 88.5, 90) (b'Lokesh', 87. , 99) (b'yashwanth', 85.5, 91)]


# 16. How to swap two rows of an array?

In [50]:
import numpy as np
sample=np.array([[1,5,4],[3,8,9],[8,2,3],[4,7,6]])
print("before swapping : ")
print(sample)
print()
print("swapping 1st and 3rd row : ")
sample[[1,3]]=sample[[3,1]]
print(sample)

before swapping : 
[[1 5 4]
 [3 8 9]
 [8 2 3]
 [4 7 6]]

swapping 1st and 3rd row : 
[[1 5 4]
 [4 7 6]
 [8 2 3]
 [3 8 9]]


# 17.  Write a Python code to reshape to the next dimension of numpy array?

In [51]:
import numpy as np 
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
x

array([[ 23,  34, 121],
       [ 23,  22,  67],
       [686, 434, 123]])

In [54]:
y=x.reshape(9,1)
y

array([[ 23],
       [ 34],
       [121],
       [ 23],
       [ 22],
       [ 67],
       [686],
       [434],
       [123]])

In [56]:
z=x.reshape(1,9)
z

array([[ 23,  34, 121,  23,  22,  67, 686, 434, 123]])